import type { Metadata } from "next";

import "./globals.css";
import "../styles/main.css";
import "../styles/font-face.css";
import "../styles/overwrite.css";
/* import "../styles/servicesPage.css"; */
import "../styles/style-pageservices.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Widget from "@/components/Widget";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
       <Navbar/>
        {children}
        <Widget/>
        <Footer/>
      </body>
    </html>
  );
}
